authorization/authorization/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("mproduct.urls"))
]

authorization/mproduct/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from mproduct.views import *

app_name = "mproduct"

urlpatterns = [
    path("",HomeView.as_view(),name='home'),
    path("login/",LoginView.as_view(template_name='mproduct/login.html'),name='login'),
    path("logout/",LogoutView.as_view(),name="logout"),
    path("register/",RegisterView.as_view(),name="register"),
    path("<str:company>/",DashboardView.as_view(),name='dashboard'),
    path("settings/",SettingsView.as_view(),name='settings'),
    path("create/Company/",CreateCompany.as_view(),name='create_Company'),
    path("create/plan/",CreatePlan.as_view(),name='create_plan'),
    # path("subscription/",SubscriptionView.as_view(),name='subscription'),
    # path("subscribers/",SubscribersView.as_view(),name='subscribers'),
    # path("subscription/status/<int:pk>/",SubscriptionStatusView.as_view(),name='status'),
    path("plans/",PlansView.as_view(),name='plans'),
    path("plans/<int:pk>/",CompanyPlansView.as_view(),name='Company_plans'),
    # path("purchase/",SubscribeView.as_view(),name='new_purchase'),
    path("search/",search_Companys,name='search_Companys'),
    path("<str:Company>/<str:BusinessUnit>/register/",EmployeeRegisterView.as_view(),name="employee_register"),
    path("<str:Company>/dashboard/",DashboardView.as_view(),name="dashboard"),
    path("invite/email/",InviteEmailView.as_view(),name='invite_email'),
]

authorization/mproduct/models.py
"""
Database info
"""

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.text import slugify
from django.utils import timezone

# Create your models here.

class Subscriber(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    company = models.CharField(max_length=30,help_text="Company Name")
    companysize = models.IntegerField(help_text="Company size")
    registered_on = models.DateTimeField(default=timezone.now)
    status = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.user.username}'
    

# @receiver(post_save,sender=User)
# def create_or_update_subscriber_profile(sender,instance,created,**kwargs):
#     if created:
#         Subscriber.objects.create(user=instance)
#     else:
#         if hasattr(instance,'subscriber'):
#             instance.subscriber.save()
#         else:
#             Subscriber.objects.create(user=instance)


class Company(models.Model):
    """
    Model to store info about variouos Companys
    """
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=30,unique=True)

    class Meta:
        unique_together = ('owner','name')

    def __str__(self) -> str:
        return self.name


class BusinessUnit(models.Model):
    """
    Model to store info about BusinessUnits from various Companys
    """
    name = models.CharField(verbose_name="BusinessUnit name",max_length=20,unique=True)
    Company = models.ForeignKey(Company,on_delete=models.CASCADE)
    head = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)

    def __str__(self) -> str:
        return f'{self.Company}-{self.name}'


class Employee(models.Model):
    """
    Model to store info about employees from different companies
    """
    employee = models.OneToOneField(User,on_delete=models.CASCADE)
    BusinessUnit = models.ForeignKey(BusinessUnit,on_delete=models.CASCADE)
    is_approved = models.BooleanField(default=False)

    def __str__(self) -> str:
        return f'{self.employee}-{self.BusinessUnit.Company}'


class Requests(models.Model):
    sender = models.ForeignKey(User,on_delete=models.CASCADE,related_name='sent_requests')
    receiver = models.ForeignKey(User,on_delete=models.CASCADE,related_name='received_requests')
    created = models.DateField()
    status = models.BooleanField()

    def __str__(self) -> str:
        return f'{self.created}-{self.sender}'

class Plans(models.Model):
    """
    Model to store information about the plans that the admin offers.
    """
    slug = models.SlugField(unique=True,blank=True)
    name = models.CharField(max_length=50,blank=False)
    Company = models.ForeignKey(Company,on_delete=models.CASCADE)
    description = models.CharField(max_length=255,blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    duration = models.IntegerField(help_text="Duration of the plan")

    def save(self,*args,**kwargs):
        self.slug = slugify(f'{self.Company.owner.username}-{self.Company.name}-{self.name}-{self.price}-{self.duration}')
        super(Plans,self).save(*args,**kwargs)

    def __str__(self) -> str:
        return f'{self.slug}'

authorization/mproduct/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from mproduct.models import Subscriber


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=254,help_text="Required. Inform a valid email address.")
    firstname = forms.CharField(max_length=10,help_text="first name",required=True)
    lastname = forms.CharField(max_length=10,help_text="last name",required=True)
    company = forms.CharField(max_length=30,help_text="company name",required=True)
    companysize = forms.IntegerField(help_text="company size",required=True)

    class Meta:
        model = User
        fields = ['username','email','password1','password2','firstname','lastname']
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['firstname']
        user.last_name = self.cleaned_data['lastname']

        if commit:
            user.save()
            subscriber = Subscriber(user=user)
            subscriber.company = self.cleaned_data['company']
            subscriber.companysize = self.cleaned_data['companysize']
            subscriber.save()
        return user

authorization/mproduct/views.py
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin
from mproduct.forms import UserRegisterForm
from django.contrib.auth.models import User
from django.views.generic import CreateView, TemplateView, ListView, UpdateView, View
from mproduct.models import Plans, Company, BusinessUnit, Employee, Requests, Subscriber
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET
from django.http import HttpRequest, HttpResponse, JsonResponse, Http404
import datetime
# Create your views here.

class RegisterView(CreateView):
    form_class = UserRegisterForm
    template_name = "mproduct/register.html"
    success_url = reverse_lazy("mproduct:login")

class HomeView(TemplateView):
    template_name = 'mproduct/home.html'

    def get_context_data(self, **kwargs: reverse_lazy):
        context = super().get_context_data(**kwargs)
        context['is_authenticated'] = self.request.user.is_authenticated
        context['is_authorized'] = False
        # context['is_authorized'] = Subscribers.objects.filter(name=self.request.user,subscription_status=True).exists() if context['is_authenticated'] else False
        context['is_Company'] = Company.objects.filter(owner=self.request.user).exists() if context['is_authorized'] else False
        context['title'] = 'Home'
        print("---------->",context)
        return context


class DashboardView(LoginRequiredMixin,TemplateView):
    login_url = 'mproduct:login'
    template_name = 'mproduct/dashboard.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Dashboard'
        context['user'] = self.request.user
        context['company'] = Subscriber.objects.filter(user=self.request.user).first()
        context['is_authorized'] = True
        context['is_authenticated'] = self.request.user.is_authenticated
        # context['is_authorized'] = Subscribers.objects.filter(name=self.request.user,subscription_status=True).exists() if context['is_authenticated'] else False
        context['is_Company'] = Company.objects.filter(owner=self.request.user).exists() if context['is_authorized'] else False
        print("->>>>>>>",context)
        return context


class InviteEmailView(LoginRequiredMixin,TemplateView):
    login_url = 'mproduct:login'
    template_name = 'mproduct/invite_email.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Dashboard'
        context['user'] = self.request.user
        context['company'] = Subscriber.objects.filter(user=self.request.user).first()
        context['is_authorized'] = True
        context['is_authenticated'] = self.request.user.is_authenticated
        # context['is_authorized'] = Subscribers.objects.filter(name=self.request.user,subscription_status=True).exists() if context['is_authenticated'] else False
        context['is_Company'] = Company.objects.filter(owner=self.request.user).exists() if context['is_authorized'] else False
        print("->>>>>>>",context)
        return context


class PlansView(LoginRequiredMixin,ListView):
    model = Plans
    template_name = 'mproduct/plans.html'
    context_object_name = 'plans'
    login_url = 'mproduct:login'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(Company=get_object_or_404(Company,name='mproduct'))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_authenticated'] = self.request.user.is_authenticated
        context['title'] = 'Plans'
        return context

class CompanyPlansView(LoginRequiredMixin,ListView):
    model = Plans
    template_name = 'mproduct/plans.html'
    context_object_name = 'plans'
    login_url = 'mproduct:login'

    def get_queryset(self):
        Company = Company.objects.get(pk=self.kwargs.get('pk'))
        queryset = super().get_queryset()
        return queryset.filter(Company=Company)

# class SubscribeView(LoginRequiredMixin,View):
#     login_url = 'mproduct:login'

#     def post(self,request,*args,**kwargs):
#         plan_id = request.POST.get('plan_id')
#         plan = get_object_or_404(Plans, id=plan_id)
#         name = request.user
#         date = timezone.now().date()
#         status = True
#         Subscribers.objects.create(name=name,plan=plan,purchased_on=date,subscription_status=status)
#         return redirect('mproduct:home')

class CreateCompany(LoginRequiredMixin,CreateView):
    login_url = 'mproduct:login'
    model = Company
    template_name = 'mproduct/settings.html'
    fields = ['name']
    success_url = reverse_lazy('mproduct:settings')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class CreatePlan(LoginRequiredMixin,CreateView):
    login_url = 'mproduct:login'
    model = Plans
    template_name = 'mproduct/settings.html'
    fields = ['name','description','price','duration']
    success_url = reverse_lazy('mproduct:settings')

    def form_valid(self, form):
        Company = Company.objects.get(owner=self.request.user)
        print("------------->Company",Company)
        form.instance.Company = Company
        return super().form_valid(form)


class SettingsView(LoginRequiredMixin,TemplateView):
    login_url = 'mproduct:login'
    template_name = 'mproduct/settings.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_authenticated'] = self.request.user.is_authenticated
        context['profile'] = get_object_or_404(User,username=self.request.user)
        # context['is_authorized'] = Subscribers.objects.filter(name=self.request.user,subscription_status=True).exists()
        context['title'] = 'Settings'
        if context['is_authorized']:
            context['is_Company'] = Company.objects.filter(owner=self.request.user).exists()
        else:
            context['is_Company'] = False
        if context['is_Company']:
            context['Company'] = Company.objects.get(owner=self.request.user)
            if Plans.objects.filter(Company=context['Company']).count() < 3:
                context['create_plans'] = True
            else:
                context['create_plans'] = False
            context['plans'] = Plans.objects.filter(Company=context['Company'])
        else:
            context['Company'] = False
        context['requests'] = Requests.objects.filter(receiver=self.request.user)
        print("------------->",context)
        return context


# class SubscriptionView(LoginRequiredMixin,ListView):
#     model = Subscribers
#     template_name = 'mproduct/subscription.html'
#     context_object_name = 'subscriptions'
#     login_url = 'mproduct:login'

#     def get_queryset(self) -> QuerySet[reverse_lazy]:
#         queryset = super().get_queryset()
#         return queryset.filter(name=self.request.user)
    
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['is_authenticated'] = self.request.user.is_authenticated
#         context['is_authorized'] = Subscribers.objects.filter(name=self.request.user,subscription_status=True).exists()
#         context['is_Company'] = Company.objects.filter(owner=self.request.user).exists()
#         context['title'] = 'Subscriptions'
#         return context

# class SubscribersView(LoginRequiredMixin,ListView):
#     model = Subscribers
#     template_name = 'mproduct/subscribers.html'
#     context_object_name = 'subscribers'
#     login_url = 'mproduct:login'

#     def get_queryset(self) -> QuerySet[reverse_lazy]:
#         queryset = super().get_queryset()
#         if Company.objects.filter(owner=self.request.user).exists():
#             Company = Company.objects.get(owner=self.request.user)
#             return queryset.filter(plan__Company=Company)
#         return queryset.none()
    
#     def get_context_data(self, **kwargs: reverse_lazy) :
#         context = super().get_context_data(**kwargs)
#         context['is_authenticated'] = self.request.user.is_authenticated
#         context['is_authorized'] = Subscribers.objects.filter(name=self.request.user,subscription_status=True).exists()
#         context['is_Company'] = Company.objects.filter(owner=self.request.user).exists()
#         context['title'] = 'Subscribers'
#         return context

# class SubscriptionStatusView(LoginRequiredMixin,UpdateView):
#     login_url = 'mproduct:login'
#     model = Subscribers
#     fields = []
#     success_url = reverse_lazy('mproduct:subscribers')

#     def form_valid(self, form):
#         subscriber = form.instance
#         end_date = subscriber.purchased_on + timezone.timedelta(days=subscriber.plan.duration)
#         if end_date > timezone.now().date():
#             subscriber.subscription_status = not subscriber.subscription_status
#         subscriber.save()
#         return super().form_valid(form)

@require_GET
def search_Companys(request):
    query = request.GET.get('data','')
    if query:
        Companys = Company.objects.filter(name__icontains=query)
        results = list(Companys.values())
    else:
        results = []
    return JsonResponse(results,safe=False)


class EmployeeRegisterView(CreateView):
    form_class = UserRegisterForm
    template_name = 'mproduct/employee_register.html'
    success_url = reverse_lazy('mproduct:login')

    def dispatch(self, request: HttpRequest, *args, **kwargs):
        Company = self.kwargs.get('Company')
        BusinessUnit = self.kwargs.get('BusinessUnit')
        self.Company = get_object_or_404(Company,name=Company)

        try:

authorization/mproduct/templates/mproduct/home.html
{% extends 'mproduct/base.html' %}

{% block pagecontent %}
<div class="container py-5">
    {% if is_authenticated %}
    <div class="d-flex flex-column align-items-center py-3">
        <div class="fs-3 my-2">Grow your business 10x with our product</div>
        <div><a href="{% url 'mproduct:plans' %}" class="btn btn-lg btn-outline-success">Get Started <i class="bi bi-arrow-right"></i></a></div>
    </div>
    <div class="row align-items-center g-0 py-3">
        <div class="col"><hr></div>
        <div class="col-1 d-flex justify-content-center fs-4">OR</div>
        <div class="col"><hr></div>
    </div>
    <div class="py-3">
        <div class="card">
            <div class="card-body">
                <div class="fs-4 fw-bold pb-3">Select a store from our range of partners</div>
                <div class="input-group">
                    <span class="input-group-text"><i class="bi bi-search"></i></span>
                    <input type="search" id="search-bar" placeholder="Start typing..." class="form-control">
                    <div id="suggestions" class="list-group position-absolute w-100" style="display: none;z-index: 1000;"></div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="d-flex justify-content-center">
        <a href="{% url 'mproduct:register' %}" class="btn btn-outline-primary">Get started</a>
    </div>
    {% endif %}
</div>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        var brandPlansUrl = '{% url "mproduct:brand_plans" 0 %}';  // Placeholder URL with dummy pk

        $('#search-bar').keyup(function() {
            var query = $(this).val();
            if (query.length > 1) {
                $.ajax({
                    url: '{% url "mproduct:search_brands" %}',
                    data: {'data': query},
                    success: function(data) {
                        console.log(data);
                        $('#suggestions').empty().hide();
                        if (data.length > 0) {
                            $.each(data, function(index, item) {
                                var itemUrl = brandPlansUrl.replace('0', item.id);  // Replace dummy pk with actual id
                                $('#suggestions').append(`<a href="${itemUrl}" class='list-group-item list-group-item-action'>` + item.name + `</a>`).show();
                            });
                        }
                    }
                });
            } else {
                $('#suggestions').hide();
            }
        });

        $(document).click(function(e) {
            if (!$(e.target).closest('#search-bar').length) {
                $('#suggestions').hide();
            }
        });
    });
</script>
{% endblock %}

authorization/mproduct/templates/mproduct/invite_csv.html
{% extends 'mproduct/base.html' %}
{% block pagecontent %}
    <div class="container">
        <div class="py-3">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-pills card-header-pills">
                        <li class="nav-item">
                            <a href="#" class="nav-link active">Invite by Email</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">Invite with a Link</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">Add by CSV</a>
                        </li>
                    </ul>
                </div>
                <div class="card-body"></div>
            </div>
        </div>
    </div>
{% endblock %}

authorization/mproduct/templates/mproduct/invite_link.html
{% extends 'mproduct/base.html' %}
{% block pagecontent %}
    <div class="container">
        <div class="py-3">
            <div class="card">
                <div class="card-header">
                    <ul class="nav nav-pills card-header-pills">
                        <li class="nav-item">
                            <a href="#" class="nav-link active">Invite by Email</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">Invite with a Link</a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">Add by CSV</a>
                        </li>
                    </ul>
                </div>
                <div class="card-body"></div>
            </div>
        </div>
    </div>
{% endblock %}

authorization/mproduct/templates/mproduct/landing.html
{% extends 'mproduct/base.html' %}

{% block pagecontent %}
<div class="container py-5">
    {% if is_authenticated %}
    <div class="d-flex flex-column align-items-center py-3">
        <div class="fs-3 my-2">Grow your business 10x with our product</div>
        <div><a href="#" class="btn btn-lg btn-outline-success">Get Started <i class="bi bi-arrow-right"></i></a></div>
    </div>
    <div class="row align-items-center g-0 py-3">
        <div class="col"><hr></div>
        <div class="col-1 d-flex justify-content-center fs-4">OR</div>
        <div class="col"><hr></div>
    </div>
    <div class="py-3">
        <div class="card">
            <div class="card-body">
                <div class="fs-4 fw-bold pb-3">Select a store from our range of partners</div>
                <div class="input-group">
                    <span class="input-group-text"><i class="bi bi-search"></i></span>
                    <input type="search" id="search-bar" placeholder="Start typing..." class="form-control">
                    <div id="suggestions" class="list-group position-absolute w-100" style="display: none;z-index: 1000;"></div>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    <div class="d-flex justify-content-center">
        <a href="{% url 'mproduct:register' %}" class="btn btn-outline-primary">Get started</a>
    </div>
    {% endif %}
</div>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>
<script>
    $(document).ready(function() {
        $('#search-bar').keyup(function() {
            var query = $(this).val();
            if (query.length > 1) {
                $.ajax({
                    url: '{% url "mproduct:search_brands" %}',
                    data: {'data':query},
                    success: function(data) {
                        // console.log(data);
                        $('#suggestions').empty().hide();
                        if (data.length > 0) {
                            $.each(data, function(index,item) {
                                $('#suggestions').append(`<a href='#' class='list-group-item list-group-item-action'>` + item.name + `</a>`).show();
                            });
                        }
                    }
                });
            } else {
                $('#suggestions').hide();
            }
        });
        $(document).click(function(e) {
            if (!$(e.target).closest('#search-bar').length) {
                $('#suggestions').hide();
            }
        });
    });
</script>
{% endblock %}

authorization/mproduct/templates/mproduct/settings.html
{% extends 'mproduct/base.html' %}
{% block pagecontent %}
    <div class="container">
        <div class="py-3">
            <div class="fs-3">Profile Details</div>
            <hr>
            <div>
                <div class="input-group mb-3">
                    <span class="input-group-text" style="min-width: 120px;">Username</span>
                    <input type="text"
                           readonly
                           class="form-control"
                           value="{{ profile.username }}">
                </div>
                <div class="input-group mb-3">
                    <span class="input-group-text" style="min-width: 120px;">Email</span>
                    <input type="text" readonly class="form-control" value="{{ profile.email }}">
                </div>
            </div>
            <div>
                <a href="#" class="btn btn-outline-danger">Change Password</a>
            </div>
        </div>
        <div class="py-3">
            <div class="fs-3">Brand Details</div>
            <hr>
            {% if is_brand %}
                <div class="input-group mb-3">
                    <span class="input-group-text" style="min-width: 120px;">Name</span>
                    <input type="text" readonly class="form-control" value="{{ brand.name }}">
                </div>
            {% elif is_authorized %}
                <div class="d-flex justify-content-center">
                    <form action="{% url 'mproduct:create_brand' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text"
                                   class="form-control"
                                   name="name"
                                   placeholder="Create your own brand"
                                   style="min-width: 300px">
                            <button type="submit" class="btn btn-dark">Create</button>
                        </div>
                    </form>
                </div>
            {% else %}
                <div>
                    <div class="d-flex justify-content-center fw-bold fs-4 mb-3">Premium comes with so much more exclusives features.</div>
                    <div class="d-flex justify-content-center">
                        <a href="{% url 'mproduct:plans' %}" class="btn btn-outline-success">Purchase now</a>
                    </div>
                </div>
            {% endif %}
        </div>
        {% if is_brand %}
            <div class="py-3">
                <div class="d-flex justify-content-between">
                    <div class="fs-3">Plans Details</div>
                    {% if create_plans %}
                        <div class="d-flex justify-content-end">
                            <button type="button"
                                    data-bs-toggle="modal"
                                    data-bs-target="#create-plan"
                                    class="btn btn-outline-success">Create New</button>
                        </div>
                    {% else %}
                        <div class="d-flex justify-content-end">
                            <button type="button"
                                    data-bs-toggle="modal"
                                    data-bs-target="#create-plan"
                                    class="btn btn-outline-success"
                                    disabled>Create New</button>
                        </div>
                    {% endif %}
                    <div class="modal fade"
                         id="create-plan"
                         tabindex="-1"
                         aria-labelledby="CreatePlan"
                         aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="CreatePlan">Plan Details</h1>
                                    <button type="button"
                                            class="btn-close"
                                            data-bs-dismiss="modal"
                                            aria-label="close"></button>
                                </div>
                                <div class="modal-body">
                                    <form action="{% url 'mproduct:create_plan' %}" method="post">
                                        {% csrf_token %}
                                        <div class="row mb-3">
                                            <div class="col">
                                                <label for="name" class="form-label">Name</label>
                                                <input type="text" name="name" placeholder="name" class="form-control">
                                            </div>
                                        </div>
                                        <div class="row mb-3">
                                            <div class="col">
                                                <label for="description" class="form-label">Description</label>
                                                <textarea name="description" placeholder="description" class="form-control"></textarea>
                                            </div>
                                        </div>
                                        <div class="row mb-3">
                                            <div class="col">
                                                <label for="price" class="form-label">Price</label>
                                                <input type="number" name="price" placeholder="price" class="form-control">
                                            </div>
                                        </div>
                                        <div class="row mb-3">
                                            <div class="col">
                                                <label for="duration" class="form-label">Duration</label>
                                                <input type="number"
                                                       name="duration"
                                                       placeholder="duration"
                                                       class="form-control">
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-success form-control">Create</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <div>
                    {% if plans %}
                        <div class="table-responsive">
                            <table class="table table-hover table-striped">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Description</th>
                                        <th>Duration</th>
                                        <th>Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for plan in plans %}
                                        <tr>
                                            <td>{{ plan.name }}</td>
                                            <td>{{ plan.description }}</td>
                                            <td>{{ plan.duration }}</td>
                                            <td>{{ plan.price }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}